# Generated by Django 3.1.7 on 2021-03-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nazwa',
            new_name='name',
        ),
    ]
