# Generated by Django 3.1.7 on 2021-03-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210327_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_last_name',
        ),
    ]
